name: HyPrimeCore
main: HyPrimeCore\CoreMain
version: "1.0-REV#201-394-675d"
api: [3.0.0+ALPHA13]
author: ["larryTheCoder"]
softdepends: ['PocketVote']
depends: ['SkyWarsForPE', 'EconomyAPI']

commands:
  cloak:
    description: "The main cloak particle command"
    default: true
  fly:
    description: "Ability to fly on air"
    default: true
    permission: "ability.fly"
  about:
    desription: "What up with our server"
    default: true
  setupinterface:
    desription: "Setup the button interface"
    default: op

permissions:
  ability.fly:
    description: "Ability to fly on air"
    default: op
  core.cloak.firerings:
    desription: "Firerings particle for all"
    default: op
  core.cloak.firewings:
    desription: "Firewings particle for all"
    default: op
  core.cloak.frosty:
    desription: "Frosty particle for all"
    default: op
  core.cloak.scanner:
    desription: "Scanner particle for all"
    default: op
  core.cloak.shaman:
    desription: "Shaman particle for all"
    default: op
  core.cloak.superhero:
    desription: "Superhero particle for all"
    default: op






